name: Release .apk
on:
  workflow_dispatch:
    inputs:
      release_name:
        required: false
        description: "Release name"
    secrets:
      BROWSERSTACK_USER:
        required: true
      BROWSERSTACK_KEY:
        required: true

jobs:
  BuildAndRelease:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Assemble debug
        run: ./gradlew assembleDebug
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: '[c${{ github.run_number }}] ${{ github.event.inputs.release_name }}'
          prerelease: true
          target_commitish: ${{ github.sha }}
          # TODO Add versionName to tag
          tag_name: 'debug-c${{ github.run_number }}'
          fail_on_unmatched_files: true
          files: app/build/outputs/apk/debug/*.apk
      - name: Send to BrowserStack
        uses: wei/curl@master
        with:
          args: -u "${{secrets.BROWSERSTACK_USER}}:${{secrets.BROWSERSTACK_KEY}}" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@app/build/outputs/apk/debug/RetroBoard-debug-v1.0-c${{ github.run_number }}.apk" -F "custom_id=IntivePatronage"
